act:
  # Enable or disable the plugin
  enable: true

farming_tweaks:
  # Enable or disable all the farming tweaks
  enable: true
  # How much XP each XP crop will drop
  crop_xp: 5
  # Crops that will drop XP up harvest when fully grown. Must be of Bukkit Ageable type.
  xp_crops:
    - WHEAT
    - CARROTS
    - POTATOES
    - BEETROOTS
    - NETHER_WART
    - COCOA

movement_tweaks:
  # Enable or disable all the movement tweaks
  enable: true

  path_speed_boost:
    # What Bukkit Material to be used to apply the effect
    block: DIRT_PATH
    # What Speed level to use. Default is 1 for Speed I. Min of 1, Max of 10.
    speed_level: 1